services:
  namenode:
    image: apache/hadoop:3.3.6
    container_name: namenode
    environment:
      - HDFS_CONF_dfs_replication=1
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    image: apache/hadoop:3.3.6
    container_name: datanode
    depends_on: [namenode]
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  resourcemanager:
    image: apache/hadoop:3.3.6
    container_name: resourcemanager
    depends_on: [namenode]
    environment:
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
      - YARN_CONF_yarn_application_classpath=/etc/hadoop/*
    ports:
      - "8088:8088"

  hive-metastore:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore
    depends_on: [namenode]
    ports:
      - "9083:9083"
    volumes:
      - ./hive/hive-site.xml:/opt/hive/conf/hive-site.xml

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    depends_on: [hive-metastore]
    ports:
      - "10000:10000"

  spark-master:
    build: ./spark
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    build: ./spark
    container_name: spark-worker
    depends_on: [spark-master]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G

  spark-driver:
    image: bitnami/spark:3.5.0
    container_name: spark-driver
    depends_on: [spark-master, hive-metastore, elasticsearch]
    volumes:
      - ./jobs:/opt/spark-apps
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: ["sleep", "infinity"]  # stays alive, run spark-submit inside

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  hadoop_namenode:
  hadoop_datanode:
  esdata: